### ISSUE TITLE
Hourglass sleep functionality is not working with Quark's "Improved Sleeping" tweak.

### ISSUE THREAD

**Issue by mortuusars** [DuckyCrayfish/hourglass#19]
I know, it is kinda expected that if some mod adds a voting system or skips the night in some other way will conflict with Hourglass. Thankfully it can be disabled easily in config. The not easy part, however, is to find out what mod adds this conflicting functionality.

So I suggest to add some info about it in **Compatibility** section of readme, or inform a users in other ways.

_Also, with quark's "Nerf Clock" tweak (which makes clock stationary until crafted) - "Display Bed Clock" icon will not move and always show midday._

**Comment by DuckyCrayfish** [comment]
Thank you for the suggestion.

What do you think of the notes I've added in a5adee6ef8ff94976709f373f1f5d89a5c4a1c93? [Link to branch.](https://github.com/DuckyCrayfish/hourglass/tree/doc/sleep-vote-mods)

Also, would you mind filling me in a little bit on the Nerf Clock option in Quark? What exactly does it do? Is it enabled by default?

**Comment by mortuusars** [comment]
Thanks for taking the time to look into this, not many people care about the "unimportant" stuff like the documentation. I'm sure this note will save some modpack maker a few hours of debugging which mod is causing incompatibility.
The only thing I'd change is naming of "**The "Nerf Clock" Quark option**" to be consistent with Quark config: Just swap words around, or use full name: "Enable Clock Nerf". Quark config is massive so people that would search for the option may miss it if words is not exact.

As for nerf itself - this is description from quark website: 
"_As a bonus, Compasses and Clocks will not function until crafted to prevent cheesing with the recipe book._"
As far as I know JEI is not showing clock rotation, so this nerf only applies to recipe book.

**Comment by DuckyCrayfish** [comment]
No problem!

The changes will be released with version 1.2.0.0.

I had trouble formatting the changes on CurseForge so I replaced the contents of the compatibility section with a link to the section on GitHub. It looks good. 
 
Thanks for providing me with details on the Clock Nerf option, I searched online but did not find anything.
