### ISSUE TITLE
Quark breaks your clock animation

### ISSUE THREAD

**Issue by WelpSTudent** [DuckyCrayfish/hourglass#31]
For some reason, quark breaks your clock animation on screen. Any way you could fix? I wrote on the quark issue github also

https://user-images.githubusercontent.com/63996164/148503361-573edac7-60ac-4827-bdad-4d1c9fd4cba0.mp4

https://user-images.githubusercontent.com/63996164/148503352-167824db-ebba-4f31-8841-060a0b42b9f0.mp4

**Comment by DuckyCrayfish** [comment]
The "Nerf Clock" feature in Quark (enabled by default) breaks the bed clock in Hourglass. Disabling this settings via Quark config fixes this issue.

There is a paragraph on Quark in the compatibility section of Hourglass that mentions this interaction.

Thanks for bringing discovered issues to my attention!
