### ISSUE TITLE
Port to version 1.18.2

### ISSUE THREAD

**Issue by DuckyCrayfish** [DuckyCrayfish/hourglass#33]
Hourglass will be ported to Minecraft version 1.18.2 after the release of MinecraftForge version 40.1.0.

Until then, the API is unstable and has changes that currently cause Hourglass to crash.

**Comment by WelpSTudent** [comment]
Interesting convo with the forge team about 40.0.18 to 40.1.0 which you might find interesting. Hopefully it sways you to updating
![image](https://user-images.githubusercontent.com/63996164/159819490-4550cf3f-c135-475e-9726-ca8cf516a10b.png)

**Comment by TheCurle** [comment]
FYI; this change was an abberation and should have been caught by our standard PR processes.

The fix has been effected; [see here](https://github.com/MinecraftForge/MinecraftForge/pull/8532) and we have changed the process to avoid this mistake happening again.

**Comment by DuckyCrayfish** [comment]
Thanks for the heads up @WelpSTudent, I'll put a priority on updating the mod instead of waiting.

For the record, the new update DID break Hourglass, which used to work just fine on Minecraft 1.18.2. I was informed by multiple Forge developers that the x.1.x release marks the release where the API is stable and will not change.

**Comment by WelpSTudent** [comment]
Sounds good! :D 
I like the mod too much to wait a few months ahah, had to put my marketing skills to work!

**Comment by DuckyCrayfish** [comment]
Hourglass port for 1.18.2 created: 087ccbb48dd48577e3208fc988e3eff5ea449500

Link to download: https://www.curseforge.com/minecraft/mc-mods/hourglass/files/3718132
