### ISSUE TITLE
(1.18.2) Crash on startup

### ISSUE THREAD

**Issue by Gavin456b** [DuckyCrayfish/hourglass#34]
[crash-2022-03-24_13.48.16-fml.txt](https://github.com/DuckyCrayfish/hourglass/files/8344554/crash-2022-03-24_13.48.16-fml.txt)

**Comment by DuckyCrayfish** [comment]
Hourglass was not compatible with Minecraft 1.18.2, but a new port for 1.18.2 has just been released. 

https://www.curseforge.com/minecraft/mc-mods/hourglass/files

**Comment by Gavin456b** [comment]
Ah, this seems to be a recurring problem. The curse browser is allowing me to install a few different mods that aren't actually updated yet.

**Comment by DuckyCrayfish** [comment]
No worries!
