### ISSUE TITLE
Update to Forge 41.1

### ISSUE THREAD

**Issue by Zygus42** [DuckyCrayfish/hourglass#39]
Crashing on startup with minimal mods installed:
[crash-2022-07-20_18.15.07-fml.txt](https://github.com/DuckyCrayfish/hourglass/files/9148847/crash-2022-07-20_18.15.07-fml.txt)

hourglass-1.19-1.2.1.0
forge-1.19-41.0.100

**Comment by DavidTheFighter** [comment]
I'm also getting this same error. It appears to be an issue with forge versions 41.0.64 and above. 41.0.63 and below work just fine.

**Comment by DuckyCrayfish** [comment]
Updated to work with Forge version 41.1.0 on Minecraft 1.19.

https://www.curseforge.com/minecraft/mc-mods/hourglass/files/3933642
