### ISSUE TITLE
Update to 1.19.1 and 1.19.2

### ISSUE THREAD

**Issue by murao-kun** [DuckyCrayfish/hourglass#41]
The 1.19 version of the mod is outdated, there is minimal changes that was made in Recommended Build of forge, but in need of being tweaked. Can you update the mod please?

**Comment by Zygus42** [comment]
Yes please - current version of Hourglass is crashing on startup with forge 1.19.1

**Comment by DuckyCrayfish** [comment]
Work on catching up to the changes in 1.19 has begun, and 1.19.1/1.19.2 should follow shortly after. 

Expect a new release tomorrow or Saturday.

**Comment by murao-kun** [comment]
[crash-2022-08-14_12.01.51-fml.txt](https://github.com/DuckyCrayfish/hourglass/files/9332990/crash-2022-08-14_12.01.51-fml.txt)
Yeah waiting on 1.19.1/1.19.2 support. Thought it may work with 1.19 version like some other mods.

**Comment by DuckyCrayfish** [comment]
Unfortunately not. Hourglass sends a couple messages and 1.19.1 tweaked the chat API in a way that breaks my compatibility. Shouldn't be a difficult fix though.

**Comment by DuckyCrayfish** [comment]
A new release for Minecraft versions 1.19.1 and 1.19.2 has just been uploaded.
