### ISSUE TITLE
Malformed `<img>` in `<a>` in description page on Modrinth

### ISSUE THREAD

**Issue by James103** [DuckyCrayfish/hourglass#45]
The description page on Modrinth for this mod has a malformed `<img>` in `<a>` at the top which should display the logo.
As a result, only a link to the image is displayed instead of the image itself.

Inspecting the raw HTML, I find the following:
```html
<a href="https://raw.githubusercontent.com/DuckyCrayfish/hourglass/main/res/logo-wide-588x256.png">
<img src alt="Hourglass Logo" width="550">
</a>
```
The HTML should be:
```html
<img src="https://raw.githubusercontent.com/DuckyCrayfish/hourglass/main/res/logo-wide-588x256.png" alt="Hourglass Logo" width="550">
```
<details>

<summary> Expected visual output (click to expand): </summary>

<img src="https://raw.githubusercontent.com/DuckyCrayfish/hourglass/main/res/logo-wide-588x256.png" alt="Hourglass Logo" width="550">

</details>

**Comment by DuckyCrayfish** [comment]
Oops, it seems that when I copied the banner from the README I accidentally replaced the <a> tag's href with the new image link instead of the <img> tag, as you may have suspected:

```
<a href="https://raw.githubusercontent.com/DuckyCrayfish/hourglass/main/res/logo-wide-588x256.png">
   <img src="res/logo/logo-wide-588x256.png" alt="Hourglass Logo" width="550">
</a>
```

Good catch, fixed.
