### ISSUE TITLE
Issue with Just Enough Resources (JER).

### ISSUE THREAD

**Issue by Zoidey** [DuckyCrayfish/hourglass#51]
This is an odd issue but I'll mention it anyway. I have noticed that Hourglass for whatever strange reason that I can't figure out is not playing nice with the Just Enough Resources (JER) mod. I'm not getting any errors or anything that I can see (I've not delved through all the logs to see if any errors relating to Hourglass or Just Enough Resources (JER) occurring).

The issue is if I have Hourglass installed then Just Enough Resources (JER) doesn't work, the tab for JER that shows you where in the world certain ores spawn range-wise, what mods drop what etc.

I just disabled Hourglass and Just Enough Resources (JER) worked but as soon as I reenabled Hourglass and loaded up Minecraft it stopped showing up, I disabled it again and it worked. Which is what has got me so puzzled.

Hourglass and Just Enough Resources (JER) are two completely different mods that do totally different things, as far as I can see they aren't similar in the slightest other than that they are both mods.

It could be Hourglass that is not compatible with Just Enough Resources (JER) or vice versa.  Either way, something strange is going on and I can't figure out why Just Enough Resources (JER) won't show up or work properly if Hourglass is installed/enabled.

I love hourglass as being able to control the length of the days and night is amazing, by default I find that the Minecraft days are too short, spend more time sleeping to skip them than doing whatever it is I'm trying to do lol.

**Comment by Zoidey** [comment]
Alright after further investigation (which I should have done from the start, but now I feel rather silly) I don't think Hourglass is interfering with Just Enough Resources as its working on and off and seems to be only working for vanilla Minecraft ores etc not ores or drops etc from other mods. I don't know how or why it would interfere in any shape or form.

JER doesn't seem to show up everything it's supposed to even for vanilla Minecraft items as such things like Mob drops work on and off. I'm running All The Mods 8 and since they have their own mods that simplify things like grouping all ores into one version rather than each mod having their own version of copper for example. Better to have just a single version of copper than to deal with like 3 or four versions of the same ore or item.

Maybe just put this issue on the back burner in case.

**Comment by DuckyCrayfish** [comment]
Thanks for the update. I'll mark the issue as stale, but I'll keep an eye on it, and we can certainly open the issue back up if more information comes up.
