### ISSUE TITLE
Support question regarding sleep time

### ISSUE THREAD

**Issue by johalun** [DuckyCrayfish/hourglass#53]
Hey

Couldn't find a discord so I'll ask here. 

Let's say I got my day speed and night speed set to some value, 0.01. Now I want to more or less disable sleep but I don't know how to do that so instead I thought I set the sleep speed to match game speed so there's no speed up when players are sleeping.

Would I set speed sleep max and min to 1.0 or to 0.01 (matching my day/night speed) to achieve this?

Thanks again!

**Comment by johalun** [comment]
Ok I did some testing and it seems the sleep speed value is relative to minecraft default speed so I need to set the value here to the same as my day speed, 0.01, for the time to not speed up while sleeping.

**Comment by DuckyCrayfish** [comment]
Great question, and your conclusion is correct.
