### ISSUE TITLE
Incompatibility with time control mod

### ISSUE THREAD

**Issue by HoodBlah** [DuckyCrayfish/hourglass#62]
Forge 1.19.2

time control mod lets you extend the day and night cycles to be as king as you want. Currently I have it set as 40 min day and 50 min night. However, with the hourglass mod the night doesn’t move at all. You can lay in bed but it won’t effect the time.

https://www.curseforge.com/minecraft/mc-mods/time-control

**Comment by CyanideX** [comment]
Not related to time control; the issue occurs without it installed. Also, you wouldn't need both mods since Hourglass can alter the day and night length.

**Comment by Answordy** [comment]
That mod does the exact same thing as hourglass, why would you use them together? Just close this issue.
