### ISSUE TITLE
Port to 1.20.1

### ISSUE THREAD

**Issue by AzureShark** [DuckyCrayfish/hourglass#67]
Is there a 1.20 and up port planned at the moment?

**Comment by DuckyCrayfish** [comment]
There absolutely is. Development will likely start October 9th, and it looks like development will not take very long to complete.

**Comment by NanoAi** [comment]
Can't wait to see it, yours is probably the best sleep mod out there.

**Comment by DuckyCrayfish** [comment]
Hey! Took me a bit longer than I anticipated, but 1.20 and 1.20.1 has been released, and 1.20.2 is on the way shortly. Thanks for waiting. Enjoy!
