### ISSUE TITLE
Day and Night Speed keeps changing to a fixed value.

### ISSUE THREAD

**Issue by TheGoldenNebula** [DuckyCrayfish/hourglass#72]
The first time the server.toml file get into my saves folder, the values of day and night speed is 1.0. I've installed the hourglass mod into my singleplayer world so that I could extend the length of day and night. Therefore I've set the values to 0.5 to both of them. Later on I noticed that nothing changed, but the night cycle is faster than normal. Later on I've checked the .toml file and saw that the Day speed is stuck at 0.6657828282828281, and night speed is stuck at 1.2827991452991454 no matter what I do or how many times I've changed the values to 0.5.

**Comment by DuckyCrayfish** [comment]
Wow that's a strange one. Would you mind sharing the other mods you have installed?

**Comment by TheGoldenNebula** [comment]
Ofcourse.

Sit (by bl4ckscor3)
Macaw's Paths and Pavings (by sketch_macaw)
[EMF] Entity Model Features [Fabric & Forge] (by traben_0)
Sophisticated Core (by P3pp3rF1y)
Skin Layers 3D (Fabric/Forge) (by tr7zw)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Placebo (by Shadows_of_Fire)
YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)
Cristel Lib (by Cristelknight)
Collective (by Serilum)
[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)
Snow Under Trees (by bl4ckscor3)
playerAnimator (by KosmX)
Festive Delight [Forge + Fabric] (by to0pa_fr)
YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
Easy Magic [Forge & Fabric] (by Fuzs)
Delightful (by brnbrd)
Savage Ender Dragon[Forge/Fabric] (by someaddon)
Oculus (by Asek3)
Smarter Farmers (farmers replant) (by MehVahdJukaar)
Bookshelf (by DarkhaxDev)
Macaw's Doors (by sketch_macaw)
YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)
Prism [Forge] (by Grend_G)
Enchantment Descriptions (by DarkhaxDev)
EnhancedVisuals (by CreativeMD)
FerriteCore (Forge) (by malte0811)
ImmediatelyFast (by RaphiMC)
Krypton Reforged (by Anthxny)
Controlling (by Jaredlll08)
Towns and Towers (by Biban_Auriu)
CreativeCore (by CreativeMD)
AttributeFix (by DarkhaxDev)
YDM's Weapon Master (by YourDailyModderx)
Create: Steam 'n' Rails (by mattentosh)
Easy Anvils [Forge & Fabric] (by Fuzs)
Butcher's Delight (by onuadan)
Construction Wand (by ThetaDev)
Entity Culling Fabric/Forge (by tr7zw)
Plushie Mod (by Link4real)
Ocean's Delight (by scouter567)
First-person Model (Forge/Fabric) (by tr7zw)
Butcher's Delight Foods (by onuadan)
YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Macaw's Windows (by sketch_macaw)
Sound Physics Remastered (by henkelmax)
Rubidium Extra (by dimadencep)
AppleSkin (by squeek502)
FPS Reducer (by bre2el)
Serene Seasons Fix (by Or_OS)
Legendary Tooltips [Forge] (by Grend_G)
Macaw's Roofs (by sketch_macaw)
Iceberg [Forge] (by Grend_G)
Small Ships [Fabric & Forge] (by talhanation)
End Remastered (by jack_bagel)
HT's TreeChop (by hammertater)
Nether's Delight (by lumpazl)
Macaw's Bridges (by sketch_macaw)
Hit Indication (by hamesterfoxxo)
Auto HUD (by Crendgrim)
Architectury API (Fabric/Forge) (by shedaniel)
YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
Cupboard (by someaddon)
Corpse (by henkelmax)
Moonlight Lib (by MehVahdJukaar)
Magnesium/Rubidium Dynamic Lights (by Anthxny)
Incendium (by Starmute)
Just Enough Items (JEI) (by mezz)
Supplementaries (by MehVahdJukaar)
Chef's Delight [Forge] (by redstone3game)
Nullscape (by Starmute)
Macaw's Lights and Lamps (by sketch_macaw)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Coffee Delight (by someoneice)
Better Combat [Fabric & Forge] (by daedelus_dev)
Embeddium (by embeddedt)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
Macaw's Trapdoors (by sketch_macaw)
Falling Leaves (Forge) (by Cheaterpaul)
Canary (by AbdElAziz333)
Not Enough Animations (by tr7zw)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Item Borders [Forge] (by Grend_G)
Fusion (Connected Textures) (by SuperMartijn642)
Cosmetic Armor Reworked (by LainMI)
Carry On (by Tschipp)
End's Delight (by foggyhillside)
Serene Seasons (by TheAdubbz)
TerraBlender (Forge) (by TheAdubbz)
Balm (Forge Edition) (by BlayTheNinth)
Visual Workbench [Forge & Fabric] (by Fuzs)
Macaw's Fences and Walls (by sketch_macaw)
Kotlin for Forge (by thedarkcolour)
Immersive Aircraft [Fabric/Forge] (by Conczin)
Magnesium/Rubidium Extras (by Anthxny)
Sophisticated Backpacks (by P3pp3rF1y)
Macaw's Furniture (by sketch_macaw)
Advancement Plaques [Forge] (by Grend_G)
NetherPortalFix (by BlayTheNinth)
YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)
Clean Swing Through Grass (by Raycoms)
Hourglass (by DuckyCrayfish)
Create Confectionery (by Furti_Two)
Farmer's Delight (by vectorwing)
Macaw's Paintings (by sketch_macaw)
AI Improvements (by QueenOfMissiles)
Villager Names (by Serilum)
Mouse Tweaks (by YaLTeR)
Curios API (Forge) (by TheIllusiveC4)
fix GPU memory leak[Forge/Fabric] (by someaddon)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Storage Drawers (by Texelsaur)
Better Fps - Render Distance[Forge] (by someaddon)
Create Slice & Dice (by possible_triangle)
Starlight (Forge) (by Spottedstar)
Creeper no Break Blocks (by Talilon)
Traveler's Titles (Forge) (by YUNGNICKYOUNG)
Searchables (by Jaredlll08)
River Redux (by Jasmine)
ItemPhysic Lite (by CreativeMD)
Create (by simibubi)
TexTrue's Embeddium Options (by TexTrue)
Cloth Config API (Fabric/Forge) (by shedaniel)
ModernFix (by embeddedt)

**Comment by DuckyCrayfish** [comment]
Ahh shoot. This is a big list. Is this a part of a mod pack?

**Comment by TheGoldenNebula** [comment]
Nope, just a personal modpack. 

Anyway the issue might be caused by the mod "Serene Season Fix." Since that mod is said to make a compatibility with serene seasons and hourglass.

**Comment by DuckyCrayfish** [comment]
That's probably what it is hahaha. Let me know. I'm going to close this issue for now.

**Comment by TheGoldenNebula** [comment]
Yup it is. Thanks alot guy!

**Comment by kocane** [comment]
@TheGoldenNebula Probably a dumb question, but what must be do to actually lengthen the days if we use Serene Seasons Fix? Is it a matter of taking in the tick in sereneseasons-server.toml?
