### ISSUE TITLE
Server-side or Client-side

### ISSUE THREAD

**Issue by fmohican** [DuckyCrayfish/hourglass#74]
Hello,
The mod can be installed only on server-side?

**Comment by Wicked1667** [comment]
No client also. Server won't let you join unless client has it too

**Comment by DuckyCrayfish** [comment]
@Wicked1667 Are you certain about this? I'm not sure this is true. I believe that for a client who does not have Hourglass installed, the server will display a red X in the client server lists (a fix for this is pending release), but they are still able to join. 

I know that one down-side is that the movement of the sky will not be smooth without the client installed, but I don't think there is anything game-breaking about the experience. 

Let me know if I'm wrong about any of this, my memory is fading from the last time I tested this situation.

**Comment by DuckyCrayfish** [comment]
I am closing this issue but we can continue to discuss.

**Comment by Wicked1667** [comment]
Yes I installed it server side then when myself and my 3 friends tried joining it gave us mod missing errors and we had to download it to join

**Comment by DuckyCrayfish** [comment]
Interesting, I wonder if this is version dependent. Do you know which version you were using? I'm going to try this when I get home.

**Comment by Wicked1667** [comment]
1.20-1.2.1.1
I added it to the CurseForge modpack "ATM9"

**Comment by DuckyCrayfish** [comment]
It seems you are correct, thanks for the clarification @Wicked1667!

I must have been getting it confused with my upcoming release, which currently does support server-side-only installations. I still need to take care of that red X tho lol
