### ISSUE TITLE
Time settings isnt working right

### ISSUE THREAD

**Issue by Thisguyneedshelp** [DuckyCrayfish/hourglass#75]
Im trying to get the game time to move in real time as in 24 hours in a day, and i thought i did the calculations for it correctly, heres my config https://mclo.gs/Ww9vPSI , but it still seems to be moving much too fast, is it possible the config just has a limit on how slowly i can make the ticks, and if so can you maybe make some sort of fix for this

**Comment by DuckyCrayfish** [comment]
I believe the correct value may be 0.00694444444445. Give that a try and if it doesn't work, please re-open the ticket.

❤️
