### ISSUE TITLE
Mod distribution on Modrinth is out of date

### ISSUE THREAD

**Issue by cyyynthia** [DuckyCrayfish/hourglass#79]
Hello!

I stumbled across your mod through [Modrinth](https://modrinth.com/mod/hourglass). Over there, the last version published is v1.2.1.1 for Minecraft Forge 1.19.1-1.19.2 (Published August 31st, 2022). I was initially very sad about the lack of 1.20.1 support, but turns out there are builds for this version available on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/hourglass).

Would it be possible to publish the missing builds on Modrinth as well?

**Comment by DuckyCrayfish** [comment]
Ahh shoot, I always forget about Modrinth.

Thanks for the heads up! I'll take care of that tonight.

**Comment by DuckyCrayfish** [comment]
Done. Thanks again for pointing that out. Enjoy!
